questions = [
    {"id": 0, "question": "\"ajalaam\" li lon ike mute!",  "effects": {"wapolan": 1}},
    {"id": 1, "question": "One ought not use a word in an atypical way.", "effects": {"wapolan": 1}},
    {"id": 2, "question": "Other proficient learners can easily understand my toki ma.", "effects": {"wapolan": 1}},
    {"id": 3, "question": "I do not change my use of toki ma until an official poll modifies it.", "effects": {"wapolan": 1}},
    {"id": 4, "question": "The only \”real\” toki ma words are the ones in the official dictionary.", "effects": {"wapolan": 1}},
    {"id": 5, "question": "I like to experiment with unusual or quirky ideas for toki ma’s grammar.", "effects": {"wapolan": -1}},
    {"id": 6, "question": "Having multiple dialects of toki ma would not be a bad thing.", "effects": {"wapolan": -1}},
    {"id": 7, "question": "There is nothing wrong with altering the spellings of toki pona \”pu\” words when using them for toki ma.", "effects": {"wapolan": -1}},
    {"id": 8, "question": "The words \”li\” and \”o\” ought to be merged.", "effects": {"wapolan": -1}},
    {"id": 9, "question": "\”o weka e kalama /w/\”!", "effects": {"wapolan": -1}},
    {"id": 10, "question": "nasin wapolan li lon pona alen ante ali!", "effects": {"ulokan": 1}},
    {"id": 11, "question": "toki ma grammar rules should (almost) never be broken.", "effects": {"ulokan": 1}},
    {"id": 12, "question": "Shevek/jan Sepeku is and always will be the ultimate authority on toki ma.", "effects": {"ulokan": 1}},
    {"id": 13, "question": "Miswritten or misspelled toki ma should be corrected.", "effects": {"ulokan": 1}},
    {"id": 14, "question": "The \”truest\” form of toki ma is the one described on the official website.", "effects": {"ulokan": 1}},
    {"id": 15, "question": "Any understandable toki ma is correct toki ma.", "effects": {"ulokan": -1}},
    {"id": 16, "question": "When in doubt of how to express something, make stuff up and hope your recipient understands it.", "effects": {"ulokan": -1}},
    {"id": 17, "question": "There are as many \”nasins\” of toki ma as there are users of toki ma.", "effects": {"ulokan": -1}},
    {"id": 18, "question": "toki ma cannot be truly taught or read about; it can only be grasped through experience and immersion.", "effects": {"ulokan": -1}},
    {"id": 19, "question": "There are no toki ma \”rules,\” only suggestions.", "effects": {"ulokan": -1}},
    {"id": 20, "question": "There will always be a need to make toki ma better.", "effects": {"ante": 1}},
    {"id": 21, "question": "Far better to have a superior version of toki ma in a few years than to settle for an inferior version in the present.", "effects": {"ante": 1}},
    {"id": 22, "question": "It is perfectly fine that old toki ma texts and translations may become obsolete in the future.", "effects": {"ante": 1}},
    {"id": 23, "question": "I have personally proposed many changes to toki ma.", "effects": {"ante": 1}},
    {"id": 24, "question": "toki ma should remain in \”alpha\” until its grammar has been perfected.", "effects": {"ante": 1}},
    {"id": 25, "question": "toki ma was literally perfect in the past, and every single change after that has ruined that absolute godly perfection.", "effects": {"ante": -1}},
    {"id": 26, "question": "We should preserve the present lexicon of toki ma, regardless of complaints.", "effects": {"ante": -1}},
    {"id": 27, "question": "Quick and sudden changes will confuse newcomers and force current toki ma speakers to unlearn what they’ve already mastered.", "effects": {"ante": -1}},
    {"id": 28, "question": "Using, teaching, and promoting toki ma is more important than perpetually tinkering with it.", "effects": {"ante": -1}},
    {"id": 29, "question": "\”Good enough\” beats chasing an illusory state of flawlessness.", "effects": {"ante": -1}}
];
